# 工作流名称
name: Java CI with Maven

# 工作流触发条件
on:
  # 定时 Cron 表达式
  schedule:
    - cron:  '5 4 * * *' # utc+8 12:05
  # 监听
  watch:
    # 当仓库被Star时，触发
    types: started

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境

    # 任务步骤
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run: java -jar target/pixiv-daily-jar-with-dependencies.jar
    - name: Commit files
      run: |
         git config --local user.email "2645047361@qq.com"
         git config --local user.name "Xiacqi1"
         git add README.md
         git commit -m "update readme.md"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
